[project]
name = "guestnest"
version = "0.1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psutil>=7.0.0",
    "rdkit>=2024.9.5",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]

[project.scripts]
guestnest = "guestnest:cli.main"
